# Generated by Django 4.2.17 on 2025-01-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0274_tax_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemServicefeesSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("exclude", models.BooleanField()),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicefees_settings",
                        to="pretixbase.item",
                    ),
                ),
            ],
        ),
    ]
